// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package provider

import (
	"context"
	"slices"

	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/service/rds"
)

func servicePackages(ctx context.Context) []conns.ServicePackage {
	v := []conns.ServicePackage{
		rds.ServicePackage(ctx),
	}

	return slices.Clone(v)
}
